FROM node:18.18.2 AS base
WORKDIR /app


# Rebuild the source code only when needed
FROM base AS builder
ARG BUILD_ENV
ARG TELEGRAM_BOT_TOKEN_MAINNET
ARG TELEGRAM_BOT_TOKEN_TESTNET
ENV BUILD_ENV=${BUILD_ENV}
ENV TELEGRAM_BOT_TOKEN_MAINNET=${TELEGRAM_BOT_TOKEN_MAINNET}
ENV TELEGRAM_BOT_TOKEN_TESTNET=${TELEGRAM_BOT_TOKEN_TESTNET}

# Production image, copy all the files and run next
FROM base AS runner
ARG BUILD_ENV
ARG TELEGRAM_BOT_TOKEN_MAINNET
ARG TELEGRAM_BOT_TOKEN_TESTNET
ENV BUILD_ENV=${BUILD_ENV}
ENV TELEGRAM_BOT_TOKEN_MAINNET=${TELEGRAM_BOT_TOKEN_MAINNET}
ENV TELEGRAM_BOT_TOKEN_TESTNET=${TELEGRAM_BOT_TOKEN_TESTNET}

COPY . /app/
RUN npm install -g pm2
RUN yarn
ENTRYPOINT yarn start:pm2:${BUILD_ENV}
EXPOSE 3333